using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WKMPMod.Generators;

[Generator]
public class RuleSourceGenerator : ISourceGenerator {
	public void Initialize(GeneratorInitializationContext context) {
		// 不需要注册语法接收器，简单全扫描即可
	}

	public void Execute(GeneratorExecutionContext context) {
		// 查找 RuleType 枚举类型
		var enumSymbol = context.Compilation.GetTypeByMetadataName("WKMPMod.Team.RuleType");
		if (enumSymbol == null) return;

		var ruleDataList = new List<(string EnumName, string CommandName, string PropertyName)>();

		// 遍历 RuleType 的所有成员
		foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>()) {
			if (member.Name == "None") continue;

			// 查找 RuleDefinitionAttribute
			var attribute = member.GetAttributes().FirstOrDefault(ad =>
				ad.AttributeClass?.Name == "RuleDefinitionAttribute" ||
				ad.AttributeClass?.Name == "RuleDefinition");

			if (attribute != null && attribute.ConstructorArguments.Length == 2) {
				string commandName = attribute.ConstructorArguments[0].Value?.ToString() ?? member.Name.ToLower();
				string propertyName = attribute.ConstructorArguments[1].Value?.ToString() ?? member.Name;
				ruleDataList.Add((member.Name, commandName, propertyName));
			}
		}

		if (ruleDataList.Count == 0) return;

		// 生成 Definitions 项
		var defMembers = ruleDataList.Select(item =>
			$"\t\t(name:\"{item.CommandName}\", type:RuleType.{item.EnumName}),"
		);
		string definitionsBody = string.Join("\n", defMembers);

		// 生成 FlattenedRule 属性 API
		var flatProps = ruleDataList.Select(item =>
			$"\tpublic bool {item.PropertyName} => (_data & (ulong)RuleType.{item.EnumName}) != 0;"
		);
		string flatPropsBody = string.Join("\n", flatProps);

		// 拼接 C# 源码
		string rawSource = $@"
// <auto-generated>
// 此代码由 Roslyn Source Generator 编译期自动生成,请勿手动修改
// </auto-generated>

using System;
using System.Collections.Generic;

namespace WKMPMod.Team;

public partial class TeamRule {{
	private static readonly List<(string name, RuleType type)> Definitions = new() {{
{definitionsBody}
	}};
}}

public readonly partial struct FlattenedRule {{
	#region [属性暴露]

{flatPropsBody}

	#endregion
}}
";
		// 行结束符标准化,免得每次生成项目都有提示
		string normalizedSource = rawSource.Replace("\r\n", "\n").Replace("\n", Environment.NewLine);
		context.AddSource("TeamRule.g.cs", SourceText.From(normalizedSource, Encoding.UTF8));
	}
}