import os

# ==============================================================================
# 1. 单一配置源头 (Single Source of Truth)
# 配置格式:
# - EnumName:     枚举名称 (大驼峰)
# - CommandName:  指令/配置名 (全小写)
# - PropertyName: 属性名 (小驼峰，FlattenedRule 暴露给外部读取 API 使用)
# - Bit:          标志位索引 (0, 1, 2, ...)
# 后续添加新规则只需复制一份配置块并修改 Bit 位即可：
# {
#     "EnumName": "NewFeature",
#     "CommandName": "newfeature",
#     "PropertyName": "newFeature",
#     "Bit": 8
# },
# ==============================================================================
RULES_CONFIG = [
    {"EnumName": "Pvp",             "CommandName": "pvp",           "PropertyName": "pvp",              "Bit": 0,},
    {"EnumName": "Hang",            "CommandName": "hang",          "PropertyName": "hang",             "Bit": 1,},
    {"EnumName": "Grab",            "CommandName": "grab",          "PropertyName": "grab",             "Bit": 2,},
    {"EnumName": "TagShow",         "CommandName": "tagshow",       "PropertyName": "tagShow",          "Bit": 3,},
    {"EnumName": "SyncSceneItem",   "CommandName": "syncsceneitem", "PropertyName": "syncSceneItem",    "Bit": 4,},
    {"EnumName": "SyncDropItem",    "CommandName": "syncdropitem",  "PropertyName": "syncDropItem",     "Bit": 5,},
    {"EnumName": "SyncInventory",   "CommandName": "syncinventory", "PropertyName": "syncInventory",    "Bit": 6,},
    {"EnumName": "SyncDied",        "CommandName": "syncdied",      "PropertyName": "syncDied",         "Bit": 7,},
    {"EnumName": "Collision",       "CommandName": "collision",     "PropertyName": "collision",        "Bit": 8,},
]

NAMESPACE = "WKMPMod.Data"
OUTPUT_FILENAME = "TeamRule.g.cs"


def generate_cs_code():
    # 1. 构建 Enum 成员定义 (基于 Bit 计算 1UL << Bit)
    enum_members = ["\tNone = 0,"]
    for item in RULES_CONFIG:
        enum_members.append(
            f"\t{item['EnumName']} = 1UL << {item['Bit']}, // {1 << item['Bit']}"
        )
    enum_body = "\n".join(enum_members)

    # 2. 构建 Definitions 列表定义
    def_members = []
    for item in RULES_CONFIG:
        def_members.append(
            f'\t\t(name:"{item["CommandName"]}", type:RuleType.{item["EnumName"]}),'
        )
    definitions_body = "\n".join(def_members)

    # 3. 构建 FlattenedRule 属性 API 暴露
    flat_props = []
    for item in RULES_CONFIG:
        flat_props.append(
            f"\tpublic bool {item['PropertyName']} => (_data & (ulong)RuleType.{item['EnumName']}) != 0;"
        )
    flat_props_body = "\n".join(flat_props)

    # 4. 拼接完整 C# 代码模版
    cs_code = f"""// <auto-generated>
//     此代码由 generate_rules.py 自动生成，请勿手动修改此文件！
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;

namespace {NAMESPACE};

// 1. 规则位图枚举
[Flags]
public enum RuleType : ulong {{
{enum_body}
}}

// 2. 队伍规则实体
public partial class TeamRule {{

\tprivate static readonly List<(string name, RuleType type)> Definitions = new() {{
{definitions_body}
\t}};

}}

// 3. 读取位图结构体
public readonly partial struct FlattenedRule {{

\t#region [属性暴露]

{flat_props_body}

\t#endregion
}}
"""

    output_path = os.path.join(os.path.dirname(__file__), OUTPUT_FILENAME)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(cs_code.strip())

    print(f"成功生成 C# 源码文件 -> {OUTPUT_FILENAME}")


if __name__ == "__main__":
    generate_cs_code()