// <auto-generated>
//     此代码由 generate_rules.py 自动生成，请勿手动修改此文件！
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;

namespace WKMPMod.Team;

// 1. 规则位图枚举
[Flags]
public enum RuleType : ulong {
	None = 0,
	Pvp = 1UL << 0, // 1
	Hang = 1UL << 1, // 2
	Grab = 1UL << 2, // 4
	TagShow = 1UL << 3, // 8
	SyncSceneItem = 1UL << 4, // 16
	SyncDropItem = 1UL << 5, // 32
	SyncInventory = 1UL << 6, // 64
	SyncDied = 1UL << 7, // 128
	Collision = 1UL << 8, // 256
}

// 2. 队伍规则实体
public partial class TeamRule {

	private static readonly List<(string name, RuleType type)> Definitions = new() {
		(name:"pvp", type:RuleType.Pvp),
		(name:"hang", type:RuleType.Hang),
		(name:"grab", type:RuleType.Grab),
		(name:"tagshow", type:RuleType.TagShow),
		(name:"syncsceneitem", type:RuleType.SyncSceneItem),
		(name:"syncdropitem", type:RuleType.SyncDropItem),
		(name:"syncinventory", type:RuleType.SyncInventory),
		(name:"syncdied", type:RuleType.SyncDied),
		(name:"collision", type:RuleType.Collision),
	};

}

// 3. 读取位图结构体
public readonly partial struct FlattenedRule {

	#region [属性暴露]

	public bool pvp => (_data & (ulong)RuleType.Pvp) != 0;
	public bool hang => (_data & (ulong)RuleType.Hang) != 0;
	public bool grab => (_data & (ulong)RuleType.Grab) != 0;
	public bool tagShow => (_data & (ulong)RuleType.TagShow) != 0;
	public bool syncSceneItem => (_data & (ulong)RuleType.SyncSceneItem) != 0;
	public bool syncDropItem => (_data & (ulong)RuleType.SyncDropItem) != 0;
	public bool syncInventory => (_data & (ulong)RuleType.SyncInventory) != 0;
	public bool syncDied => (_data & (ulong)RuleType.SyncDied) != 0;
	public bool collision => (_data & (ulong)RuleType.Collision) != 0;

	#endregion
}