<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="LocalPaths.props" Condition="Exists('LocalPaths.props')" />
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>WKMultiPlayerMod</AssemblyName>
		<Product>WKMultiPlayerMod</Product>
		<Version>1.7.6</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>WKMultiPlayerMod</RootNamespace>
		<!-- 统一输出到解决方案的 bin 目录 -->
		<!-- <OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath> -->
		<!-- 项目本身的 bin 目录 -->
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<Target Name="ValidateLocalPaths" BeforeTargets="Build" Condition="'$(GamePath)' == ''">
		<Error Text="GamePath is not set. Copy LocalPaths.props.example to LocalPaths.props and set your local game path." />
	</Target>

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>

	<!-- AfterTargets="PostBuildEvent"表示在生成完成后执行 -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- 创建名为 SharedOutputFiles 的项列表 -->
		<ItemGroup>
			<SharedOutputFiles Include="$(TargetDir)$(TargetName).dll" />
			<SharedOutputFiles Include="$(ProjectDir)Util\Localization\*.json" />
		</ItemGroup>
		<!--生成.dll复制到bin\解决方案配置-->
		<Copy SourceFiles="@(SharedOutputFiles)"
			  DestinationFolder="$(SolutionDir)bin\$(Configuration)\"
			  SkipUnchangedFiles="true" />

		<ItemGroup>
			<AllOutputFiles Include="$(SolutionDir)bin\$(Configuration)\**\*.*" />
		</ItemGroup>

		<Copy Condition="'$(GamePath)' != ''"
			  SourceFiles="@(AllOutputFiles)"
			  DestinationFolder="$(GamePath)\BepInEx\plugins\MP\%(RecursiveDir)"
			  SkipUnchangedFiles="true" />

	</Target>

	<PropertyGroup>
		<ManagedPath>$(GamePath)\White Knuckle_Data\Managed</ManagedPath>
		<BepInExPath>$(GamePath)\BepInEx\core</BepInExPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(ManagedPath)\Assembly-CSharp.dll" Private="False" />
		<Reference Include="$(ManagedPath)\Unity*.dll" Private="False" />
		<Reference Include="$(ManagedPath)\ALINE.dll" Private="False" />
		<Reference Include="$(ManagedPath)\Facepunch.Steamworks.Win64.dll" Private="False" />
		<Reference Include="$(ManagedPath)\Newtonsoft.Json.dll" Private="False" />
		<Reference Include="$(ManagedPath)\DOTween.dll" Private="False" />

		<Reference Include="$(BepInExPath)\*.dll" Exclude="$(BepInExPath)\0Harmony20.dll" Private="False" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\WKMultiPlayerMod.Shared.csproj" />
	</ItemGroup>

</Project>
