<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>WKMultiPlayerMod</AssemblyName>
		<Product>WKMultiPlayerMod</Product>
		<Version>1.5.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>WKMultiPlayerMod</RootNamespace>
		<!-- 统一输出到解决方案的 bin 目录 -->
		<!-- <OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath> -->
		<!-- 项目本身的 bin 目录 -->
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>

	<!-- AfterTargets="PostBuildEvent"表示在生成完成后执行 -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- 创建名为 SharedOutputFiles 的项列表 -->
		<ItemGroup>
			<SharedOutputFiles Include="$(TargetDir)$(TargetName).dll" />
			<!-- 包含 JSON 文件 -->
			<SharedOutputFiles Include="$(ProjectDir)Util\Localization\*.json" />
		</ItemGroup>
		<!--生成.dll复制到bin\解决方案配置-->
		<Copy SourceFiles="@(SharedOutputFiles)" DestinationFolder="$(SolutionDir)bin\$(Configuration)\" SkipUnchangedFiles="true" />
		<!--生成.dll复制到游戏文件夹-->
		<Copy SourceFiles="@(SharedOutputFiles)" DestinationFolder="D:\GAME\Steam\steamapps\common\White Knuckle\BepInEx\plugins\MP" SkipUnchangedFiles="true" />
	</Target>

	<ItemGroup>
		<Reference Include="..\..\lib\BepInEx\*.dll">
			<Private>False</Private>
		</Reference>

		<Reference Include="..\..\lib\GameData\*.dll">
			<Private>False</Private>
		</Reference>

		<Reference Include="..\..\lib\Unity\*.dll">
			<Private>False</Private>
		</Reference>

		<Reference Include="..\..\lib\Shared\*.dll">
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <None Remove="NetWork\MPPacketRouter.cs~RF634c4182.TMP" />
	</ItemGroup>

</Project>
